### ISSUE TITLE
Site Content: Update Tracking

### ISSUE THREAD

**Issue by wslack** [18F/intake#16]
- [x] Cost/IAA Info: https://github.com/18F/writing-lab/issues/46
- [x] Introducing 18F: https://github.com/18F/writing-lab/issues/47
- [x] Get to know 18F: https://github.com/18F/writing-lab/issues/48
- [x] Working with 18F: https://github.com/18F/writing-lab/issues/49
- [x] Past Work: https://github.com/18F/writing-lab/issues/50

cc @awfrancisco, @StephaniePlageman, and @kate

**Comment by wslack** [comment]
@awfrancisco and @StephaniePlageman I think I can close this?

**Comment by awfrancisco** [comment]
Yup. Though maybe open up a new issue to track design fixes/review?
