### ISSUE TITLE
1 Pagers: Update Tracking

### ISSUE THREAD

**Issue by wslack** [18F/intake#17]
- [ ] Intake 1 Pager - Data Services: https://github.com/18F/writing-lab/issues/34
- [ ] Intake 1 Pager - Consulting: https://github.com/18F/writing-lab/issues/35
- [ ] Intake 1 Pager - Delivery: https://github.com/18F/writing-lab/issues/36
- [ ] Intake 1 Pager - Federalist: https://github.com/18F/writing-lab/issues/37
- [ ] Intake 1 Pager - Infrastructure: https://github.com/18F/writing-lab/issues/38
- [ ] Intake 1 Pager - Intake Process: https://github.com/18F/writing-lab/issues/39
- [ ] Intake 1 Pager - RFP Ghostwriting: https://github.com/18F/writing-lab/issues/40

cc @StephaniePlageman, @StephanieRivera, @awfrancisco
